### PR TITLE
work on getting binder back up

### PR DESCRIPTION
**Pull request by bollwyvl**
Trying a few things here...

[Binder](https://mybinder.org/v2/gh/bollwyvl/robotkernel/update-binder?urlpath=lab)

### CODE REVIEW

**Comment by bollwyvl** [comment]
Looks like as of d9fb545 we're back in the binder business... trying a few other tweaks, but this is probably ready to be reviewed/cherry-picked. @datakurre let me know if you want anything else done!

**Comment by datakurre** [comment]
@bollwyvl If it runs, I'll love it. Trying out.

**Comment by datakurre** [comment]
@bollwyvl Thank you! Now I really owe you fixing wavelibrary :heart:

**Comment by datakurre** [comment]
I'm going to cherry pick these

**Comment by datakurre** [comment]
Merged into https://github.com/robots-from-jupyter/robotkernel/pull/55

**Comment by bollwyvl** [comment]
Ystävä: you don't owe me _anything_... this stuff is all amazing future shiny laser sword nonsense, we all just have to make our way in the universe.

On the a11y front: I've solved _part_ of my problem (static docs sites) with node (gah) and puppeteer (gaaaah) with https://github.com/pa11y/pa11y-ci. But it works in headless CI, and generates a JSON report for every page in a `sitemap.xml`, so I can't spin my wheels too hard there.

I _still_ want test tools that i can run against crazy stuff like lab, at the selector level, and WAVE might indeed be the best tool for the job, but we need to keep our options open. For example, you can't turn WAVE _off_ without reloading the page, so it would be pretty harsh/slow tests anyway.

I mean really, how hard could it be to implement all `standards x checklist items x compliance levels`? It seems like something that rightfully belongs in SL core... maybe I can dig up some grant $$$ next year to work on it.

**Pull request closed without merging**
